Peter inviting team members
mintlify/connect pull request #60
Opened 2022-05-18 04:20 UTC by petercrackthecode

Finally got this done!!

2022-05-18 04:58 UTC, hahnbeelee requested changes
When I'm on http://localhost:3000/settings# I get this error
<img width="808" alt="image" src="https://user-images.githubusercontent.com/55263191/168960353-8f4cbb3d-8757-4951-81c5-c89c1052361c.png">

2022-05-18 04:58 UTC, hahnbeelee commented on server/src/routes/user.ts
> +// import mongoose from "mongoose";
delete

2022-05-18 04:58 UTC, hahnbeelee commented on server/src/routes/user.ts
> +    console.log("orgId = ", orgId);
delete

2022-05-18 04:58 UTC, hahnbeelee commented on server/src/routes/user.ts
> +      console.log(err);
delete

2022-05-18 04:58 UTC, hahnbeelee commented on server/tsconfig.json
> -    "noImplicitReturns": true /* Report error when not all code paths in function return a value. */,
is there a reason why you changed this to false?

2022-05-18 04:58 UTC, hahnbeelee commented on web/pages/index.tsx
> +                            {[].length > 5 ? <span className="flex-shrink-0 text-xs leading-5 font-medium">+1</span> : null}
Isn't this always going to return false?

2022-05-18 04:58 UTC, hahnbeelee commented on web/pages/settings.tsx
> +    console.log("user = ", user);
remove

2022-05-18 05:18 UTC, hahnbeelee commented on web/pages/settings.tsx
> +    axios.get(`${API_ENDPOINT}/routes/org/list-users?orgId=${user.org}`).then((res) => {
I think you just need to change `${user.org}` to `${user.org._id}`. You might need to delete your instances of your org/user because it might be following an outdated data structure.

2022-05-18 05:40 UTC, hahnbeelee commented
We should also implement the Edit functionality if it's do-able or comment it out if we want to do it later.
<img width="493" alt="image" src="https://user-images.githubusercontent.com/55263191/168964987-e1d5646e-f1ac-43bb-8dd7-7a507a8acb88.png">

2022-05-18 05:58 UTC, hahnbeelee commented
Is there a way to change this message so it's more along the lines of "You have been invited"?
<img width="776" alt="image" src="https://user-images.githubusercontent.com/55263191/168965370-6c8090be-f5a7-4f20-b306-1deb3f944271.png">

2022-05-18 05:58 UTC, hahnbeelee commented
Is there a way to change this message so it's more along the lines of "You have been invited"?
<img width="776" alt="image" src="https://user-images.githubusercontent.com/55263191/168965370-6c8090be-f5a7-4f20-b306-1deb3f944271.png">

2022-05-18 08:07 UTC, petercrackthecode commented on web/pages/index.tsx
> +                            {[].length > 5 ? <span className="flex-shrink-0 text-xs leading-5 font-medium">+1</span> : null}
I didn't work on that part. It was copied directly from the main branch. I think Han worked on it. @hanywang2 any idea?

2022-05-18 08:10 UTC, petercrackthecode commented on server/tsconfig.json
> -    "noImplicitReturns": true /* Report error when not all code paths in function return a value. */,
I think that was a mistake. Turning it back to `true` now.

2022-05-19 02:45 UTC, hahnbeelee approved these changes
LGTM! Great work.

2022-05-19 02:45 UTC, merged